# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BCaCpp <- function(y, sumy, n, B, G, alpha) {
    .Call(`_giniVarCI_BCaCpp`, y, sumy, n, B, G, alpha)
}

tjackknife <- function(y, n, B, G) {
    .Call(`_giniVarCI_tjackknife`, y, n, B, G)
}

tlinearization <- function(y, n, B, G) {
    .Call(`_giniVarCI_tlinearization`, y, n, B, G)
}

tlinearizationA <- function(y, n, B, G) {
    .Call(`_giniVarCI_tlinearizationA`, y, n, B, G)
}

Linearization <- function(y, G, n, meany) {
    .Call(`_giniVarCI_Linearization`, y, G, n, meany)
}

LinearizationA <- function(y, G, n, meany) {
    .Call(`_giniVarCI_LinearizationA`, y, G, n, meany)
}

NormalityCpp <- function(y, G, n, meany) {
    .Call(`_giniVarCI_NormalityCpp`, y, G, n, meany)
}

OgwangJackknife <- function(SORTy, G, n, sumy, sumiy) {
    .Call(`_giniVarCI_OgwangJackknife`, SORTy, G, n, sumy, sumiy)
}

Order <- function(x, y) {
    .Call(`_giniVarCI_Order`, x, y)
}

Sort <- function(x) {
    .Call(`_giniVarCI_Sort`, x)
}

emplikBootCpp <- function(y, G, n, B, precisionEL, maxiterEL, alpha) {
    .Call(`_giniVarCI_emplikBootCpp`, y, G, n, B, precisionEL, maxiterEL, alpha)
}

emplikCpp <- function(y, sumy, G, n, criticalvalue, precisionEL, maxiterEL) {
    .Call(`_giniVarCI_emplikCpp`, y, sumy, G, n, criticalvalue, precisionEL, maxiterEL)
}

fginindex1Rcpp <- function(y, w, n) {
    .Call(`_giniVarCI_fginindex1Rcpp`, y, w, n)
}

fginindex2Rcpp <- function(y, w, n) {
    .Call(`_giniVarCI_fginindex2Rcpp`, y, w, n)
}

fginindex3Rcpp <- function(y, w, n) {
    .Call(`_giniVarCI_fginindex3Rcpp`, y, w, n)
}

fginindex4Rcpp <- function(y, w, n) {
    .Call(`_giniVarCI_fginindex4Rcpp`, y, w, n)
}

fginindex5Rcpp <- function(y, w0, n) {
    .Call(`_giniVarCI_fginindex5Rcpp`, y, w0, n)
}

giniMeansRcpp <- function(SORTx) {
    .Call(`_giniVarCI_giniMeansRcpp`, SORTx)
}

iginindex10Rcpp <- function(y, n, bc, Matrix, NumCol) {
    .Call(`_giniVarCI_iginindex10Rcpp`, y, n, bc, Matrix, NumCol)
}

iginindex1Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex1Rcpp`, y, n, bc)
}

iginindex2Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex2Rcpp`, y, n, bc)
}

iginindex3Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex3Rcpp`, y, n, bc)
}

iginindex4Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex4Rcpp`, y, n, bc)
}

iginindex5Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex5Rcpp`, y, n, bc)
}

iginindex7Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex7Rcpp`, y, n, bc)
}

iginindex8Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex8Rcpp`, y, n, bc)
}

iginindex9Rcpp <- function(y, n, bc) {
    .Call(`_giniVarCI_iginindex9Rcpp`, y, n, bc)
}

pBootstrap <- function(y, n, B, alpha) {
    .Call(`_giniVarCI_pBootstrap`, y, n, B, alpha)
}

rpBootstrap <- function(y, w, n, B, alpha, method) {
    .Call(`_giniVarCI_rpBootstrap`, y, w, n, B, alpha, method)
}

wJackknife <- function(y, w, Delta, n, Ghat, Nhat, varformula, PiU, N, ORDER, reOrder, method) {
    .Call(`_giniVarCI_wJackknife`, y, w, Delta, n, Ghat, Nhat, varformula, PiU, N, ORDER, reOrder, method)
}

wLinearization <- function(y, w, Delta, n, Ghat, Nhat, MeanW, varformula, PiU, N) {
    .Call(`_giniVarCI_wLinearization`, y, w, Delta, n, Ghat, Nhat, MeanW, varformula, PiU, N)
}

wLinearizationA <- function(reOrder, w, ySORT, wSORT, Delta, n, Ghat, Nhat, MeanW, varformula, PiU, N) {
    .Call(`_giniVarCI_wLinearizationA`, reOrder, w, ySORT, wSORT, Delta, n, Ghat, Nhat, MeanW, varformula, PiU, N)
}

